spring.application.name=schemalab
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/schemalab}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:schemalab}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:schemalab}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
server.port=8080
